apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nodeapp.name }}-clusterip-service

spec:
  type: {{ .Values.nodeapp.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.nodeapp.image.exposedPort }}
  
  selector:
    server: {{ .Values.nodeapp.name }}