apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.nginx.name }}-loadbalancer-service

spec:
  type:  {{ .Values.nginx.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.nginx.image.containerPort }}
  
  selector:
    server:  {{ .Values.nginx.name }}